config/routes.rb
Rails.application.routes.draw do
  # get 'potin/index'
  # get 'potin/show'

  root to: 'potin#index' #url de base du site

  get '/team', to: 'page#team'
  get '/contact', to: 'page#contact'
  get '/welcome/:user_entry', to: 'page#welcome'

  
  get 'potin/show'
  get 'potin/showuser'

  resources :potin

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_gossip_tags
    has_many :tag, through: :join_gossip_tags
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/join_private_message_recipient.rb
class JoinPrivateMessageRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_gossip_tags
    has_many :gossips, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city 
    has_many :gossip
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id]) #on récupère l'id passé en index qui ressort dans le show
  end

  def showuser
    @gossip = Gossip.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossips</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/contact.html.erb
<h1>Nous contacter</h1>
<p>Les informations de contact ci-dessous</p>


<%= link_to "clique ici pour voir notre équipe", team_path %>.

app/views/page/team.html.erb
<h1>La super équipe</h1>
<p>Voici notre super équipe</p>


<%= link_to "clique ici pour voir nous contacter", contact_path %>.

app/views/page/welcome.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Accueil</a>
</nav>


<p> </p>
BIENVENUE <%= params[:user_entry] %> ! Ici c'est notre super site de potins, il est chouette, non ?

<p> </p>
<%= link_to "clique ici pour accéder au site", root_path %> 

app/views/potin/index.html.erb
<% @gossips.each do |gossip| %>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">

    <div> 
    
    <%= gossip.title %></h5>
 
    <p class="card-text"> le lien ci dessous</p>



        <a href="#" class="btn btn-primary">
        <%= link_to "accéder à la page du gossip", potin_path(gossip) %></a>
        
          </div>
</div>
        </h2> 
    </div>





<% end %>


       <%# <%= link_to "lien vers le Gossip --> #{gossip.title}", potin_path(gossip) %></a> %>

<%# on est sur la view index donc on peut récupérer les objets du controller %>
<%# link to remplace balise a\ %>

app/views/potin/show.html.erb
<h1>Bienvenue sur la page du potin n° <%=params[:id] %> </h1>

<h2>
<%=
@gossip.title
%>
</h2>

<p> <u> le contenu du potin est le suivant, </u>
<%=
@gossip.content
%>
</p>


<p>
Créé à 
<%=
@gossip.created_at.to_date
%>

</p>

        <%= link_to "accéder à la page de l'auteur du gossip", potin_showuser_path(params[:id]) %></a>

app/views/potin/showuser.html.erb
<h1>Bienvenue sur la page de l'auteur du potin n° <%=params[:id] %> </h1>


<h2>
<%=
@gossip.user
%>
</h2>


<p> <u> le contenu du potin est le suivant, </u>
<%=
@gossip.content
%>
</p>